name: Create Security Fix Pull Request
on:
  push:
    barnches:
      - master

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1 # Node.js 環境の構築
        with:
          node-version: "10.x"

      - uses: actions/checkout@master # リポジトリを読み込み
      - with:
        repository: "muruso/action-practice"

      - run: npm install -g npm

      - run: npm -v
      - run: npm install -g yarn

      - run: yarn add typescript

      - name: Create Pull Request # ブランチを作成して PullRequest を作成
        id: cpr
        uses: peter-evans/create-pull-request@v1.7.0
        with:
          title: Security Update into master.
          labels: Auto PR
          branch: securityFix #作成されるブランチは securityFix-xxxxxxx
          token: ${{ secrets.MURUSO_SECRET }}
