name: Create Security Fix Pull Request
on:
  push:
    barnches:
      - master

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v1 # Node.js 環境の構築
        with:
          node-version: "10.x"

      - uses: actions/checkout@v2
        with:
          path: main

      - uses: actions/checkout@v2 # リポジトリを読み込み
        with:
          repository: "muruso/action-practice"
          token: ${{ secrets.MURUSO_SECRET }}
          path: action-practice

      - run: npm install -g npm

      - run: npm -v
      - run: npm install -g yarn

      - run: yarn add typescript

      - run: git status

      - name: Create Pull Request # ブランチを作成して PullRequest を作成
        id: cpr
        uses: peter-evans/create-pull-request@v3
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          title: Security Update into master.
          labels: Auto PR
          branch: feature/update-package
          token: ${{ secrets.MURUSO_SECRET }}
